# Generated by Django 6.0 on 2026-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('technicien', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Audit', 'Audit'), ('Installation', 'Installation'), ('Réparation', 'Réparation'), ('Autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='Planifiée', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EngineeringIntervention',
                'ordering': ['-date'],
            },
        ),
    ]
