# Generated by Django 6.0 on 2026-01-02 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('date_embauche', models.DateTimeField()),
                ('salaire', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En congé', 'En congé')], default='Actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('duree', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Sortie', 'Sortie'), ('Retard', 'Retard'), ('Mission', 'Mission'), ('Autre', 'Autre')], max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='hr.employee')),
            ],
            options={
                'db_table': 'Authorization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('montant', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('projet', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Transport', 'Transport'), ('Repas', 'Repas'), ('Hébergement', 'Hébergement'), ('Fournitures', 'Fournitures'), ('Autre', 'Autre')], max_length=50)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='hr.employee')),
            ],
            options={
                'db_table': 'ExpenseReport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('jours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('Congé annuel', 'Congé annuel'), ('Congé maladie', 'Congé maladie'), ('Congé sans solde', 'Congé sans solde'), ('Congé maternité', 'Congé maternité'), ('Congé paternité', 'Congé paternité')], max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ],
            options={
                'db_table': 'LeaveRequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('heure_entree', models.TimeField()),
                ('heure_sortie', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('heures', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('Heures supplémentaires', 'Heures supplémentaires'), ('Télétravail', 'Télétravail')], default='Normal', max_length=50)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('hs_valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='hr.employee')),
            ],
            options={
                'db_table': 'TimeRecord',
                'ordering': ['-date'],
            },
        ),
    ]
