# Generated by Django 6.0 on 2026-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('doc_type', models.CharField(db_column='docType', max_length=255)),
                ('year', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'CodeCounter',
                'unique_together': {('department', 'doc_type', 'year')},
            },
        ),
    ]
