# Generated by Django 5.2.9 on 2026-01-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=100)),
                ('chefProjet', models.CharField(max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('progression', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('En pause', 'En pause'), ('Annulé', 'Annulé')], default='En cours', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Devis', 'Devis'), ('Technique', 'Technique'), ('Administratif', 'Administratif'), ('Autre', 'Autre')], max_length=50)),
                ('date', models.DateField()),
                ('size', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docsList', to='projects.project')),
            ],
        ),
    ]
