# Generated by Django 6.0 on 2026-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Devis', 'Devis'), ('Technique', 'Technique'), ('Administratif', 'Administratif'), ('Autre', 'Autre')], max_length=50)),
                ('departement', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('taille', models.CharField(max_length=50)),
                ('minio_path', models.CharField(blank=True, db_column='minioPath', max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Document',
                'ordering': ['-created_at'],
            },
        ),
    ]
