# Generated by Django 5.2.9 on 2026-01-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('dateEmbauche', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En congé', 'En congé')], default='Actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('duree', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='rh.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('designation', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projet', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rh.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('jours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('type', models.CharField(max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='rh.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('heureEntree', models.TimeField()),
                ('heureSortie', models.TimeField()),
                ('lieu', models.CharField(default='Bureau', max_length=100)),
                ('heures', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(default='Normal', max_length=50)),
                ('statut', models.CharField(default='Présent', max_length=50)),
                ('hsValide', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='rh.employee')),
            ],
        ),
    ]
