# Generated by Django 4.2.8 on 2026-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('formateur', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('participants', models.IntegerField(default=0)),
                ('duree', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='Planifiée', max_length=20)),
            ],
        ),
    ]
